### ISSUE TITLE
Into The Breach-style tile labels

### ISSUE THREAD

**Issue by u-lulu** [delzhand/isocon#248]
Hello! I love this app, it's wonderful for running Maleghast.

I've noticed that it includes chess-style tile labels, which is great, but I'm interested in a version of this option that looks more like Into The Breach, as seen below:
![pasted image 0](https://github.com/delzhand/isocon/assets/18232881/8761c490-6724-4a8e-94a2-7f0478645de2)

I know this is less feasible for larger board sizes, but a toggle would be nice.

Thank you!

**Comment by delzhand** [comment]
Since you can now see other players' movement arrows and the clone/delete row/column tools show attached areas, block indicators are no longer necessary. Closing this for now.
