### ISSUE TITLE
Breaks if exceeding 30 blocks high

### ISSUE THREAD

**Issue by McPalm** [delzhand/isocon#315]
If you stack more than 30 block on top of eachother the game starts generating error messages due to a hard coded limit in the block obscuration method. Should perhaps have an set height limit across the whole app.

**Comment by delzhand** [comment]
Technically a hard cap of 30 isn't necessary except for performance reasons, but at minimum the app should use a toast error when you try to create something that tall instead of breaking, similar to what happens when you try to delete a block at height 0
