### ISSUE TITLE
Add method in Block for selecting adjacent tiles either orthogonally or diagonally

### ISSUE THREAD

**Issue by delzhand** [delzhand/isocon#318]

**Comment by McPalm** [comment]
Im thinking, there could be an utility for grabbing blocks in a specific shape, could be useful for all kinds of operations. So for focusing a column/row in #316, the function could be called to get all blocks in a column, and then use that collection to focus all of them.

**Comment by delzhand** [comment]
I think the building block here is finding a single adjacent tile in any direction, everything else is mostly iteration, eg a plus shape is just calling it on the same block with different offsets, a line loops over the last affected block, etc. The challenges here will probably be around Hidden block/elevation edge cases. Maybe it should just apply to every block in the adjacent column that's an edge piece and not hidden.

**Comment by McPalm** [comment]
Yeah, it should not be hard to implement. Im more concerned with how you do the call. My thought would be that you could do a
```cs
static public Blocks[] GetBlocks(params Vector3Int[] coordinates){}
```
method located somwhere, and it would jut get you all the requested blocks at those coordinates. It could be utilized in a block to get its neighbor by just sending in the expected coordinates of its neighbors. It could also be used by specialized scripts to return crosses, diagonals, lines, and what have you. It should probably have a Vector2Int implementation as well that just grabs the topmost block in a column.

**Comment by delzhand** [comment]
I think that's a good place to start. Maybe there should be a CoordinateUtility class that has static functions taking v2ints and returning v2ints[]s - just to keep the math part separate from block lookup. I think there's already a "get neighbors" function somewhere, we should either expand on that or abstract it from wherever it lives.

**Comment by McPalm** [comment]
Sounds good, I can make this, and Ill dive into current block lookups and see how it can fit together.
