### ISSUE TITLE
Cloning higher terrain onto tokes conceals them

### ISSUE THREAD

**Issue by McPalm** [delzhand/isocon#324]
https://github.com/delzhand/isocon/assets/22002617/9860b00c-165f-4da7-bcca-b267d38d705c

If completely encased, they also become unselectable.

**Comment by delzhand** [comment]
I think the solution here is that on map sync, if a token's position is below the top block of their new column, move them to it. This might result in the occasional unnecessary move when a token would otherwise be in a valid lower level of a multi level architecture, but I think it's acceptable.

**Comment by delzhand** [comment]
See discussion on #331
