### ISSUE TITLE
6x8 maps from Maleghast Map Maker do not import properly

### ISSUE THREAD

**Issue by u-lulu** [delzhand/isocon#373]
Attempting to import [this map](https://alessandrominali.github.io/maleghast/map?w=6&h=8&m=KzAMpEDYpUHYBMj6io8iYdFhzVpZJwQg):
![image](https://github.com/delzhand/isocon/assets/18232881/4333bd46-0dfd-4707-ba7a-cd42a2b4de37)

Results in the map being loaded like this into the editor:
![image](https://github.com/delzhand/isocon/assets/18232881/74d9e51d-23a7-4ff1-bf14-d47d43e9f6cf)

It seems to be a general issue with 6x8 maps, as any 6x8 map I create and import does not seem to assemble properly.

**Comment by delzhand** [comment]
Oh, I've clearly got the length and width reversed. That'll be an easy fix.

**Comment by delzhand** [comment]
On second glance that doesn't seem exactly right, but hopefully it's still an easy fix

**Comment by delzhand** [comment]
Fixed for 0.7.x release
