### ISSUE TITLE
Wound display not working in focus info

### ISSUE THREAD

**Issue by delzhand** [delzhand/isocon#61]

**Comment by kimeyu** [comment]
I believe I found the root cause for this.  I'll remind myself how to make a pull request and try to put that up.

**Comment by kimeyu** [comment]
Well, I think I have a fix for the floater HP bar as soon as I can get write permissions.  The focus info panel one, not yet.  The code for it exists commented out (https://github.com/delzhand/isocon/blob/66b4f2e9ba44025c476ded7d7f043b52a871fa0c/Assets/Scripts/Token/UnitState.cs#L65-L72), but looks like the UI element isn't there right now, bunch of errors when trying it out.
